version: "2.4"

services:
  model_trainer:
    build:
      context: .
      dockerfile: trainer.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - akdata:/app/akdata
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis:
    image: "redis:6.2"

volumes:
  akdata:
