version: "3.8"

services:
  model_trainer:
    build:
      context: .
      dockerfile: trainer.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - model_data:/app/data
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

 ## webui:
 ##   build:
 ##     context: .
  ##    dockerfile: Dockerfile.webui
 ##   ports:
 ##     - "3000:3000"
 ##   depends_on:
 ##     - model_trainer

  redis:
    image: "redis:6.2"

volumes:
  model_data:
